import os

configfile: "../config/config.yaml"

# Setup conda/micromamba activation if specified
# If not specified or path doesn't exist, assume conda is already activated
if "micromamba_path" in config and "micromamba_env" in config:
    micromamba_path = os.path.expandvars(config["micromamba_path"])
    micromamba_env = config["micromamba_env"]
    if os.path.exists(micromamba_path):
        shell.prefix(f"source {micromamba_path}; micromamba activate {micromamba_env}; ")

include: "rules/setup.smk"

rule all:
    input:
        get_all_inputs()

include: "rules/star_alignment.smk"
include: "rules/process_bam.smk"
include: "rules/bam_to_fastq.smk"
include: "rules/salmon.smk"
include: "rules/variant_calling.smk"
include: "rules/filtering.smk"
include: "rules/annotations.smk"
include: "rules/query_vcfs.smk"
include: "rules/process_features.smk"
include: "rules/classify_variants.smk"